[package]
name = "binance"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
async-trait.workspace = true
thiserror.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true

domain = {path = "../../domain"}
execution ={ path = "../../execution"}

hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

urlencoding = {version = "2.1.3"}
tokio-tungstenite = { version = "0.28", features = ["rustls-tls-native-roots"] }
futures-util = "0.3"